package com.undeadscythes.supergenes.gui;

import com.undeadscythes.authenticmd.service.*;
import com.undeadscythes.genebase.*;
import com.undeadscythes.supergenes.*;
import com.undeadscythes.supergenes.service.*;
import com.undeadscythes.tipscript.*;
import java.io.*;
import javax.swing.*;

/**
 * The main GUI window to server the {@link SuperGenesGUI} services.
 *
 * @author Dave
 */
public class SuperGenesGUI extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;
    private static SuperGenes program;
    private static TipRedirect output;

    /**
     * Creates new form SuperGenesGUI
     */
    public SuperGenesGUI() {
        initComponents();
        for (GeneBase geneBase : program.getGeneBases()) {
            menuGeneBases.add(new JMenuItem(geneBase.getUID().toString()));
            itemNoGeneBases.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        menu = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        itemLoad = new javax.swing.JMenuItem();
        seperator1 = new javax.swing.JPopupMenu.Separator();
        itemQuit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuGeneBases = new javax.swing.JMenu();
        itemNoGeneBases = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SuperGenes");

        menuFile.setText("File");

        itemLoad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        itemLoad.setText("Load");
        itemLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLoadActionPerformed(evt);
            }
        });
        menuFile.add(itemLoad);
        menuFile.add(seperator1);

        itemQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        itemQuit.setText("Quit");
        itemQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemQuitActionPerformed(evt);
            }
        });
        menuFile.add(itemQuit);

        menu.add(menuFile);

        menuEdit.setText("Edit");
        menu.add(menuEdit);

        menuGeneBases.setText("GeneBases");

        itemNoGeneBases.setText("No GeneBases Loaded");
        itemNoGeneBases.setEnabled(false);
        itemNoGeneBases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNoGeneBasesActionPerformed(evt);
            }
        });
        menuGeneBases.add(itemNoGeneBases);

        menu.add(menuGeneBases);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemQuitActionPerformed
        this.dispose();
    }//GEN-LAST:event_itemQuitActionPerformed

    private void itemLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLoadActionPerformed
        final JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(Thread.currentThread().getContextClassLoader().getResource("").getPath()));
        chooser.setFileFilter(new GEDFilter());
        if (chooser.showOpenDialog(this) == JFileChooser.CANCEL_OPTION) return;
        final Load load = new Load();
        load.run(program, chooser.getSelectedFile().getPath());
        if (load.getGeneBase() != null) {
            menuGeneBases.add(new JMenuItem(load.getGeneBase().getUID().toString()));
            itemNoGeneBases.setVisible(false);
        }
        JOptionPane.showMessageDialog(this, output.getOutput(), "SuperGenes", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_itemLoadActionPerformed

    private void itemNoGeneBasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNoGeneBasesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNoGeneBasesActionPerformed

    /**
     * Initiate the GUI from the given {@link SuperGenes} program.
     */
    public static void main(final SuperGenes program, final TipRedirect output) {
        SuperGenesGUI.program = program;
        SuperGenesGUI.output = output;

        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperGenesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperGenesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperGenesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperGenesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperGenesGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemLoad;
    private javax.swing.JMenuItem itemNoGeneBases;
    private javax.swing.JMenuItem itemQuit;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuGeneBases;
    private javax.swing.JPopupMenu.Separator seperator1;
    // End of variables declaration//GEN-END:variables
}
